const example = '```json\n{\n  "network": "xera-http",\n  "security": "tls",\n  "xeraHttpSettings": {\n    "path": "/connect",\n    "mode": "auto"\n  }\n}\n```'

const headings = ['Транспорт Xera HTTP', 'Xera HTTP transport', 'انتقال Xera HTTP', 'Xera HTTP 传输']
const rows = [
    [
        ['Совместимость', 'Xera HTTP — собственный HTTP-транспорт нашего Xray. Для подключения он должен поддерживаться и ядром ноды, и ядром клиентского приложения. Обычный Xray с поддержкой XHTTP не обязательно понимает Xera. Проверяйте наличие network: "xera-http" в обеих сборках. Не меняйте действующий профиль для всех пользователей сразу: сначала клонируйте его и проверьте отдельный хост.'],
        ['Compatibility', 'Xera HTTP is a custom HTTP transport in our Xray core. Both the node core and the client application core must support it. XHTTP support in a regular Xray build does not imply Xera support. Check that both builds accept network: "xera-http". Clone a working profile and test a separate host before changing it for all users.'],
        ['سازگاری', 'Xera HTTP یک انتقال HTTP اختصاصی در هسته Xray ما است. هسته نود و هسته برنامه کاربر هر دو باید از آن پشتیبانی کنند. پشتیبانی XHTTP در Xray معمولی به معنی پشتیبانی Xera نیست. بررسی کنید هر دو بیلد network: "xera-http" را می‌پذیرند. پیش از تغییر برای همه کاربران، پروفایل فعال را کپی و یک هاست جدا را آزمایش کنید.'],
        ['兼容性', 'Xera HTTP 是我们 Xray 内核中的自定义 HTTP 传输。节点内核和客户端内核都必须支持它。普通 Xray 支持 XHTTP 不代表支持 Xera。确认两端构建都接受 network: "xera-http"。先克隆可用配置并测试独立主机，再为所有用户切换。']
    ],
    [
        ['Настройка профиля', 'В [профиле](/dashboard/management/config-profiles) откройте JSON и задайте network: "xera-http" в streamSettings нужного inbound. Параметры находятся в xeraHttpSettings. Ниже показан фрагмент streamSettings, а не полный inbound: сохраните свои tlsSettings, клиентов, порт и остальные параметры. Для TLS нужны действительный сертификат и соответствующий домен. Для REALITY используйте security: "reality" и свои realitySettings.\n\n' + example],
        ['Profile configuration', 'Open JSON in a [profile](/dashboard/management/config-profiles) and set network: "xera-http" in the inbound streamSettings. Transport options belong in xeraHttpSettings. The example below is a streamSettings fragment, not a complete inbound: retain your tlsSettings, clients, port and other settings. TLS requires a valid certificate and a matching domain. For REALITY, use security: "reality" and your realitySettings.\n\n' + example],
        ['تنظیم پروفایل', 'در [پروفایل](/dashboard/management/config-profiles) ویرایشگر JSON را باز کنید و در streamSettings ورودی موردنظر، network: "xera-http" را قرار دهید. گزینه‌ها در xeraHttpSettings هستند. نمونه زیر فقط بخشی از streamSettings است و ورودی کامل نیست؛ tlsSettings، کاربران، پورت و تنظیمات دیگر خود را حفظ کنید. TLS به گواهی معتبر و دامنه منطبق نیاز دارد. برای REALITY از security: "reality" و realitySettings خود استفاده کنید.\n\n' + example],
        ['配置设置', '在[配置](/dashboard/management/config-profiles)中打开 JSON，将对应入站的 streamSettings.network 设为 "xera-http"。传输参数放在 xeraHttpSettings 中。下面只是 streamSettings 片段，并非完整入站，请保留自己的 tlsSettings、用户、端口和其他设置。TLS 需要有效证书及匹配域名。使用 REALITY 时设置 security: "reality" 并保留自己的 realitySettings。\n\n' + example]
    ],
    [
        ['Нода, хост и подписка', 'Активируйте inbound на совместимой ноде, разрешите его во внутреннем скваде и привяжите к нему [хост](/dashboard/management/hosts). В хосте укажите внешний адрес, порт и SNI. Поля «Путь» и «Host» могут переопределить значения профиля для клиента; они должны соответствовать тому, что принимает сервер или прокси. Обновите подписку тестового пользователя. Xray JSON сохраняет xeraHttpSettings; ссылки подключения содержат type=xera-http и xeraSettings. Клиент должен понимать этот формат. Генераторы Sing-box, Clash и Mihomo такие хосты пропускают, поскольку не поддерживают этот транспорт.'],
        ['Node, host and subscription', 'Activate the inbound on a compatible node, permit it in an internal squad and link a [host](/dashboard/management/hosts). Set the public address, port and SNI on the host. Path and Host fields can override profile values for the client; they must match what the server or proxy accepts. Refresh a test user subscription. Xray JSON retains xeraHttpSettings; share links carry type=xera-http and xeraSettings. The client must understand this format. Sing-box, Clash and Mihomo generators skip these hosts because they do not support this transport.'],
        ['نود، هاست و اشتراک', 'ورودی را روی نود سازگار فعال کنید، در گروه داخلی اجازه دهید و یک [هاست](/dashboard/management/hosts) به آن وصل کنید. آدرس عمومی، پورت و SNI را در هاست تنظیم کنید. فیلدهای Path و Host می‌توانند مقادیر پروفایل را برای کاربر جایگزین کنند؛ باید با مقادیر پذیرفته‌شده سرور یا پروکسی یکسان باشند. اشتراک کاربر آزمایشی را به‌روز کنید. Xray JSON گزینه xeraHttpSettings را حفظ می‌کند؛ لینک‌ها type=xera-http و xeraSettings دارند. برنامه کاربر باید این قالب را بشناسد. تولیدکننده‌های Sing-box، Clash و Mihomo این هاست‌ها را حذف می‌کنند چون این انتقال را پشتیبانی نمی‌کنند.'],
        ['节点、主机与订阅', '在兼容节点启用入站，在内部群组中授权，并关联一个[主机](/dashboard/management/hosts)。填写公网地址、端口和 SNI。主机的 Path 与 Host 可覆盖配置中发送给客户端的值，必须与服务器或代理接受的值一致。更新测试用户的订阅。Xray JSON 保留 xeraHttpSettings；分享链接包含 type=xera-http 和 xeraSettings，客户端必须识别此格式。Sing-box、Clash 和 Mihomo 生成器会跳过这些主机，因为它们不支持此传输。']
    ],
    [
        ['Режимы и HTTP-прокси', 'Начните с mode: "auto". Доступны также stream-auto, packet-up, stream-up и stream-one. Для размещения данных upload в заголовке или cookie и для метода GET требуется packet-up. На клиенте и сервере согласуйте path, host и изменённые параметры заголовков. Если перед нодой стоит HTTP-прокси, проверьте передачу нужного пути и заголовков, поддержку длительных запросов и отсутствие буферизации потокового ответа. Ошибка 404 обычно требует проверки пути и виртуального хоста; TLS-ошибка — SNI и сертификата.'],
        ['Modes and HTTP proxies', 'Start with mode: "auto". Other modes are stream-auto, packet-up, stream-up and stream-one. Upload data in headers or cookies and the GET method require packet-up. Match path, host and any customized header options on both sides. With an HTTP proxy in front of the node, check forwarding of the chosen path and headers, long-running requests and unbuffered streaming responses. For HTTP 404, check the path and virtual host. For TLS errors, check SNI and the certificate.'],
        ['حالت‌ها و پروکسی HTTP', 'با mode: "auto" شروع کنید. حالت‌های دیگر stream-auto، packet-up، stream-up و stream-one هستند. قرار دادن داده ارسال در هدر یا cookie و روش GET به packet-up نیاز دارد. path، host و گزینه‌های هدر تغییرکرده را در دو طرف هماهنگ کنید. اگر جلوی نود پروکسی HTTP قرار دارد، انتقال مسیر و هدرها، درخواست‌های طولانی و پاسخ جریانی بدون بافر را بررسی کنید. برای خطای 404 مسیر و میزبان مجازی و برای خطای TLS، SNI و گواهی را بررسی کنید.'],
        ['模式与 HTTP 代理', '先使用 mode: "auto"。还支持 stream-auto、packet-up、stream-up 和 stream-one。通过请求头或 cookie 上传数据，以及使用 GET 方法，都要求 packet-up。两端的 path、host 和自定义请求头参数必须一致。节点前有 HTTP 代理时，检查路径和请求头转发、长连接请求及流式响应是否禁用缓冲。HTTP 404 应检查路径与虚拟主机；TLS 错误应检查 SNI 和证书。']
    ],
    [
        ['Дополнительное заполнение трафика', 'customDownlinkPadding добавляет случайные байты к передаваемым блокам и увеличивает расход трафика. Начинайте без него. При включении задайте одинаковые header и token на обеих сторонах: header должен начинаться с X- и содержать 3–64 символа, token — 16–128 символов base64url. Не используйте служебные заголовки прокси. bytes допускает 0–1024, blockBytes — 1024–16384; budgetPercent ограничивает дополнительный расход (до 100%), burstBytes — начальный запас (до 1 МиБ), uplink включает заполнение upload. Эти параметры не заменяют TLS/REALITY и не гарантируют обход блокировки.'],
        ['Additional traffic padding', 'customDownlinkPadding adds random bytes to transmitted blocks and increases traffic usage. Start without it. When enabled, set matching header and token values on both sides: header must start with X- and contain 3–64 characters; token must contain 16–128 base64url characters. Avoid reserved proxy headers. bytes accepts 0–1024 and blockBytes 1024–16384; budgetPercent caps overhead (up to 100%), burstBytes is the initial allowance (up to 1 MiB), and uplink enables upload padding. These settings do not replace TLS/REALITY or guarantee that a connection bypasses blocking.'],
        ['افزودن داده تصادفی', 'customDownlinkPadding به بلوک‌های انتقال داده بایت‌های تصادفی اضافه می‌کند و مصرف ترافیک را افزایش می‌دهد. ابتدا بدون آن شروع کنید. هنگام فعال‌سازی، header و token یکسان در دو طرف قرار دهید؛ header باید با X- شروع شود و ۳–۶۴ نویسه داشته باشد و token شامل ۱۶–۱۲۸ نویسه base64url باشد. از هدرهای رزروشده پروکسی استفاده نکنید. bytes محدوده ۰–۱۰۲۴ و blockBytes محدوده ۱۰۲۴–۱۶۳۸۴ را می‌پذیرند. budgetPercent سربار را تا ۱۰۰٪ محدود می‌کند، burstBytes ذخیره اولیه تا ۱ MiB است و uplink افزودن داده در ارسال را فعال می‌کند. این تنظیمات جایگزین TLS/REALITY نیستند و عبور از مسدودسازی را تضمین نمی‌کنند.'],
        ['额外流量填充', 'customDownlinkPadding 在传输块中添加随机字节，会增加流量消耗。先不启用它。启用时两端设置相同的 header 和 token：header 必须以 X- 开头，长度 3–64 字符；token 为 16–128 个 base64url 字符。不要使用代理保留请求头。bytes 范围为 0–1024，blockBytes 为 1024–16384；budgetPercent 限制额外开销，最大 100%；burstBytes 为初始额度，最大 1 MiB；uplink 启用上传填充。这些参数不能代替 TLS/REALITY，也不保证绕过封锁。']
    ],
    [
        ['Проверка результата', 'Проверьте JSON в редакторе и сохраните профиль. Сохранение в базе и применение на ноде — разные этапы: проверьте очередь, состояние и журнал ноды. Затем заново скачайте подписку и сравните network, path, mode и SNI в клиентском конфиге. «Неизвестный транспорт» означает, что выбранное ядро не поддерживает Xera. Если хост отсутствует, проверьте сквад, доступ, фильтры и тип подписки. При нестабильности вернитесь к auto без дополнительного заполнения и меняйте по одному параметру.'],
        ['Verify the result', 'Validate JSON in the editor and save the profile. Database persistence and application on a node are separate stages: check the queue, node status and logs. Download the subscription again and compare network, path, mode and SNI in the client configuration. “Unknown transport” means the selected core does not support Xera. If the host is missing, check squads, access, filters and subscription format. For unstable connections, return to auto without additional padding and change one option at a time.'],
        ['بررسی نتیجه', 'JSON را در ویرایشگر بررسی و پروفایل را ذخیره کنید. ذخیره در پایگاه داده و اعمال روی نود دو مرحله جدا هستند؛ صف، وضعیت و گزارش نود را بررسی کنید. اشتراک را دوباره دریافت و network، path، mode و SNI را در تنظیمات کاربر مقایسه کنید. «انتقال ناشناخته» یعنی هسته انتخاب‌شده Xera را پشتیبانی نمی‌کند. اگر هاست نیست، گروه، دسترسی، فیلترها و قالب اشتراک را بررسی کنید. برای ارتباط ناپایدار به auto بدون داده تصادفی برگردید و هر بار یک گزینه را تغییر دهید.'],
        ['验证结果', '在编辑器验证 JSON 并保存配置。数据库保存与节点应用是不同阶段，请检查队列、节点状态和日志。重新下载订阅，比较客户端配置中的 network、path、mode 和 SNI。“未知传输”表示所选内核不支持 Xera。主机缺失时检查群组、访问权限、筛选条件和订阅格式。连接不稳定时回到 auto，关闭额外填充，每次只调整一个参数。']
    ]
]
const languages = ['ru', 'en', 'fa', 'zh']
export const xeraGuide = {
    id: 'xera-transport', category: 'profiles',
    ...Object.fromEntries(languages.map((language, index) => [language, headings[index]])),
    sources: ['src/widgets/dashboard/config-profiles/config-editor/', 'src/shared/ui/forms/hosts/base-host-form/'],
    route: '/dashboard/management/config-profiles', resources: ['config-profiles', 'hosts'],
    sections: rows.map((row, index) => ({
        id: `xera-transport-${index + 1}`,
        ...Object.fromEntries(languages.map((language, i) => [language, { title: row[i][0], body: row[i][1] }]))
    }))
}
